---
- name: Install Packages and Dependencies
  block:
    - name: Install AGS AUR Packages | {{ ansible_distribution }}
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: present
        use: "{{ pacman.aur_helper }}"
      become: false
      loop:
        - aylurs-gtk-shell-git
        - bun-bin
        - matugen-bin
        - wayshot

    - name: Install AGS Dependencies | {{ ansible_distribution }}
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - swww
        - dart-sass
        - fd
        - brightnessctl
        - gnome-bluetooth-3.0
        - libdbusmenu-gtk3
        - libnotify
        - libsoup3
        - networkmanager
        - power-profiles-daemon
        - upower
        - accountsservice
        - pavucontrol
        # wayshot dependiences
        - slurp
        - wf-recorder
        - wl-clipboard
        - swappy

    - name: Install AGS Greetd Dependencies | {{ ansible_distribution }}
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - greetd
        - cage
