---
- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "pre_tasks/system/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

- name: Start Systemd Services
  block:
    - name: Start systemd services
      ansible.builtin.systemd:
        state: started
        name: "{{ item.name }}"
        enabled: "{{ item.enabled | default('yes') }}"
        scope: "{{ item.scope | default(omit) }}"
      become: "{{ item.become | default(true) }}"
      loop:
        - name: systemd-timesyncd
        - name: xdg-user-dirs-update.service
          scope: user
          become: false
        - name: bluetooth
          when: system.enable_bluetooth

- name: Fixes
  block:
    - name: Gtk Window Buttons
      command: "gsettings set org.gnome.desktop.wm.preferences button-layout {{ system.gtk.buttons }}"

    - name: Ensure HoldoffTimeoutSec is set to 5 in /etc/systemd/logind.conf
      lineinfile:
        path: /etc/systemd/logind.conf
        regexp: '^#?HoldoffTimeoutSec='
        line: 'HoldoffTimeoutSec=5'
        state: present
      become: true
       
