---
- name: "Fastfetch | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: fastfetch_distribution_config

- name: "Fastfetch | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: fastfetch_distribution_config.stat.exists

- name: "Fastfetch | Configure Fastfetch"
  ansible.builtin.copy:
    src: fastfetch
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
